### ISSUE TITLE
Update zombiezen driver to v1.1.0

### ISSUE THREAD

**Issue by ffmiruz** [cvilsmeier/go-sqlite-bench#6]
zombiezen.com/go/sqlite v1.1.0 has improvement for string conversion. In context of this benchmark, fixed the outlier performance for Large case.

**Comment by cvilsmeier** [comment]
Thank you, I will update all drivers to their new versions when the next release cycle happens.

**Comment by ncruces** [comment]
Meanwhile I've updated my [fork](https://github.com/ncruces/go-sqlite-bench/tree/master#benchmarks), which should give you an idea of the expected results.

**Comment by gedw99** [comment]
> Meanwhile I've updated my [fork](https://github.com/ncruces/go-sqlite-bench/tree/master#benchmarks), which should give you an idea of the expected results.

@ncruces thats a huge performance leap. Well done.

**Comment by ncruces** [comment]
> @ncruces thats a huge performance leap. Well done.

If you mean the `zombiezen` improvement, that's not my work. @ffmiruz takes the [credit](https://github.com/zombiezen/go-sqlite/pull/66). 😆

If you mean improvements to my driver, this [PR](https://github.com/ncruces/go-sqlite3/pull/52) is responsible for the bulk of the improvement (this time around). I bet a similar approach would help other `database/sql` drivers.

A similar approach to binding values _might_ improve insert performance. I'll evaluate it in the future against increased complexity.

The rest is profiling, and focusing on reducing allocations in the hot path (the low level APIs benefit because `database/sql` itself generates some garbage).

My low level API does better than my `database/sql` driver, but I'm not sure it's appropriate for me to overwhelm the benchmark with two implementations of my own. Most people seem to prefer the `database/sql` abstraction.
